### ISSUE TITLE
[RuntimeException] image size and title size is not the same

### ISSUE THREAD

**Issue by rosuH** [AbbyJM/XBanner#1]
It was thrown a exception while filling the banner.
Here is the exception info:

> FATAL EXCEPTION: main
                                                                                    Process: com.example.rosuh.fragmenttestdemo, PID: 19278
                                                                                    java.lang.RuntimeException: image size and title size is not the same
                                                                                    size of images: 5
                                                                                    size of titles: 10
                                                                                    if you do Not need titles,please set the banner type to non-title type
                                                                                        at com.app.abby.xbanner.XBanner.checkImageAndTitleNum(XBanner.java:948)
                                                                                        at com.app.abby.xbanner.XBanner.start(XBanner.java:841)

Here are my code:

```java
        imageUrls = new ArrayList<>();
        titles = new ArrayList<>();
        for (int i = 0; i < 5; i ++) {
            imageUrls.add(mArticleItems.get(i).getImageUrl());
            titles.add(mArticleItems.get(i).getTitle());
        }
        mXBanner.isAutoPlay(true)
                .setBannerTypes(CIRCLE_INDICATOR_TITLE)
                .setDelay(3000)
                .setImageUrls(imageUrls)
                .setTitles(titles)
                .setImageLoader(new AbstractUrlLoader() {
                    @Override
                    public void loadImages(Context context, String url, ImageView image) {
                        Glide.with(context)
                                .load(url)
                                .into(image);
                    }

                    @Override
                    public void loadGifs(String url, GifImageView gifImageView
                            , ImageView.ScaleType scaleType) {

                    }
                })
                .start();
```

- - - - -
- As you can see, Image size  and title size are  the same. 
- This problem occurs when I try to repopulate xbanner.
    - I encapsulated the filling method, and then called when the page is refreshed

I also check those size in the DEBUG mode and they were the same.
So I was stuck.

Please help me to figure out the problem.
Thanks~

**Comment by AbbyJM** [comment]
It seems like the title is dumplicated.I try to fix this in the updated version.You can try 1.5.3 and see if it is solved.You can check out the titles and images once after you filling your arrays and see if they are the same size.Thank you.
